BookManagement/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns,static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include(('management.urls','management'),namespace='management')),
    #path('', include(('management.urls', 'management'), namespace='management')),
]
if settings.DEBUG:
    urlpatterns+=staticfiles_urlpatterns()
    urlpatterns+=static(settings.MEDIA_URL,document_root=settings. MEDIA_ROOT)

management/urls.py
from django.urls import path
from management import views
urlpatterns=[
	path('',views.index,name='index'),
	#path('sign_up/',views.sign_up,name='sign_up'),
	#path('login/',views.login,name='login'),
#	path('logout/'views.logout,name='logout'),
#	path('change_password/',views.change_password,name='change_password'),
	path('add_book/',views.add_book,name='add_book'),
	path('add_image/',views.add_image,name='add_image'),
	path('book_list/<str:category>/',views.book_list,name='book_list'),
	path('content/<int:book_id>/',views.content,name='content'),
	path('edit_book/<int:book_id>/',views.edit_book,name='edit_book'),
	path('delete/<int:book_id>/',views.delete,name='delete'),
]

management/models.py
from django.db import models

# Create your models here.
class Book(models.Model):
    name=models.CharField(max_length=20,verbose_name='书籍名称')
    author=models.CharField(max_length=30,verbose_name='作者')
    price=models.FloatField(verbose_name='定价',default=0.0)
    publish_date=models.DateTimeField(verbose_name='出版时间',null=True,blank=True)
    category=models.CharField(verbose_name='书籍分类',max_length=10,default='未分类')
    create_datetime=models.DateTimeField(auto_now_add=True,verbose_name='添加日期')
    def __str__(self):
        return self.name
class Image(models.Model):
    name=models.CharField(max_length=50,verbose_name='图片名称')
    description=models.TextField(verbose_name='图片描述',default='')
    img=models.ImageField(upload_to='img/%Y/%m/%d',verbose_name='图片')
    book=models.ForeignKey(Book,on_delete=models.CASCADE,verbose_name='所属书籍')
    def __str__(self):
        return self.name

management/forms.py
from django import forms
from management.models import Book,Image
class BookForm(forms.ModelForm):
	class Meta:
		model=Book
		fields=['text']

management/views.py
from django.shortcuts import render
from management.models import Book
from django.http import HttpResponseRedirect
from django.contrib.auth import authenticate
from django.urls import reverse
import time
# Create your views here.
def index(request):
	book=Book.objects.all()
	context={'books':book}
	return render(request,'management/index.html',context )
def add_book(request):
	if request.method =='POST':
		new_book=Book(
				name=request.POST.get('name',''),
				author=request.POST.get('author',''),
				category=request.POST.get('category',''),
				price=request.POST.get('price',''),
				publish_date=request.POST.get('publish_date'),
				create_datetime=request.POST.get('create_datetime'),
			)
		new_book.create_datetime=time.strftime('%Y%m%d%H%I')
		new_book.save()
		return HttpResponseRedirect(reverse('management:index'))
	return render(request,'management/add_book.html')
def add_image(request):
	if request.method == 'POST':
		new_image=Image(
				name=request.POST.get('name',''),
				description=request.POST.get('description',''),
				img=request.POST.get('imag',''),
				book=request.POST.get('book',''),
			)
		new_image.save()
		return HttpResponseRedirect(reverse('management:index'))
	return render(request,'management/add_image.html',{'books':Book.objects.all()})
def book_list(request,category):
	books=Book.objects.filter(category=category)
	return render(request,'management/book_list.html',{'books':books})
def content(request,book_id):
	book=Book.objects.get(id=book_id)
	return render(request,'management/content.html',{'book':book})
def edit_book(request,book_id):
	book=Book.objects.get(id=book_id)
	if request.method =='POST':
		book.author=request.POST.get('author','')
		book.price=request.POST.get('price','')
		book.publish_date=request.POST.get('publish_date','')
		book.category=request.POST.get('category','')
		book.save()
		return HttpResponseRedirect(reverse('management:index'))
	return render(request,'management/edit_book.html',{'book':book})
def delete(request,book_id):
	book=Book.objects.get(id=book_id)
	book.delete()
	return HttpResponseRedirect(reverse('management:index'))

management/templates/management/add_book.html
{% extends "management/base.html" %}
<!DOCTYPE html>
<html>
<head>
	<title></title>
</head>
<body>
{% block content %}
<form method="post" action="{% url 'management:add_book' %}">
	{% csrf_token %}
	name:<input type="text" name="name" required>
	author:<input type="text" name="author" required>
	price:<input type="number" name="price" required>
	publish_date:<input type="date" name="publish_date" required>
	category:<input type="text" name="category" required>
	
	<button type="submit">submit</button>
</form>
{% endblock content %}
</body>
</html>

management/templates/management/add_image.html
{% extends "management/base.html" %}
<!DOCTYPE html>
<html>
<head>
	<title></title>
</head>
<body>
	{% block content %}
	<form action="{% url 'management:add_image' %}" method="post">
		{% csrf_token %}
		name:<input type="text" name="name">
		description:<input type="text" name="description">
		img:<input type="file" name="imag">
		所属书籍:<select name="book">
			{% for book in books %}
				<option value="{{book.id}}">{{book.name}}</option>
			{% endfor %}
		</select>
		<button type="submit">提交</button>
	</form>
	{% endblock content %}
</body>
</html>

management/templates/management/base.html
<!DOCTYPE html>
<html>
<head>
	<title></title>
</head>
<body>
	<div style="height: 30px; background-color: #000000;">
		<span style="color: #ffffff;">
			图书管理系统
		</span>
		<a href="{% url 'management:add_book' %}" style="color: #ffffff">add_book</a>
		<a href="{% url 'management:add_image' %}" style="color: #ffffff">add_img</a>
		<a href="{% url 'management:index' %}" style="color: #ffffff">主页</a>
		{% block title %}
		{% endblock title %}
	</div>
{% block content %}
{% endblock content %}
</body>
</html>

management/templates/management/book_list.html
{% extends "management/base.html" %}
<!DOCTYPE html>
<html>
<head>
	<title></title>
</head>
<body>
	{% block content %}
	{% for book in books %}
	<p>
		{{book}}
	</p>
	{% endfor %}
	{% endblock content %}
</body>
</html>

management/templates/management/content.html
{% extends "management/base.html" %}
<!DOCTYPE html>
<html>
<head>
	<title></title>
</head>
<body>
{% block content %}
<p>
	名称：{{book.name}}
</p>
<p>
	作者：
	{{book.author}}
</p>
<p>
	出版时间：
	{{book.publish_date|date:'Y-m-d'}}
</p>
<p>
	价格：{{book.price}}
</p>
<p>
	分类：
	{{book.category}}
</p>
<p>
	书籍上传时间:
	{{book.create_datetime|date:'Y-m-d H:i'}}
</p>
{% endblock content %}
</body>
</html>

management/templates/management/edit_book.html
{% extends "management/base.html" %}
<!DOCTYPE html>
<html>
<head>
	<title></title>
</head>
<body>
	{% block content %}
<p>你好</p>
<span>您在修改</span><span style="color: blue;">{{book.name}}</span><span>图书</span>
<form action="{% url 'management:edit_book' book.id %}" method="post">
	{% csrf_token %}
	author:<input type="text" name="author" value="{{book.author}}" required>
	price:<input type="text" name="price" value="{{book.price}}" required>
	publish_date:<input type="date" name="publish_date" value="{{book.publish_date|date:'Y-m-d'}}" required>
	category:<input type="text" name="category" value="{{book.category}}" required>
	<button type="submit">submit</button>
</form>
{% endblock content %}
</body>
</html>

management/templates/management/index.html
{% extends "management/base.html" %}
<!DOCTYPE html>
<html>
<head>
	<title></title>
</head>
<body>
<p>This is BookManagement</p>
{% block content %}
{% for book in books %}
<p>
	书名：{{book.name}}
</p>
<p>
	作者：{{book.author}}
</p>

<a href="{% url 'management:content' book.id %}">具体信息</a>
<a href="{% url 'management:book_list' book.category %}">查看此类书籍</a>
<a href="{% url 'management:edit_book' book.id %}">编辑</a>
<a href="{% url 'management:delete' book.id %}">删除</a>
{% endfor %}
{% if user %}
{{user.name}}
{% endif %}
{% endblock content %}
</body>
</html>

management/templates/management/sign_up.html
{% extends "management/base.html" %}
<!DOCTYPE html>
<html>
<head>
	<title></title>
</head>
<body>
{% block title %}
<p>注册</p>
{% endblock title %}
{% block content %}
<form method="post" action="{% url management:sign_up %}">
	{% csrf_token %}
	<h1>
		请注册:
	</h1>
	用户名:<input type="text" name="username" required>
	密码:<input type="password" name="password">
	电子邮件:<input type="email" name="email">
	<button type="submit">注册</button>
</form>
{% endblock content %}
</body>
</html>